[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

# API routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Convenience aliases
[[redirects]]
  from = "/available-secrets"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/approve"
  to = "/approve/index.html"
  status = 200
